# Generated by Django 4.2.5 on 2023-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to="C:\\works\\DjangoSample\\project\\media\\['Q', 'm', '6', 'j', 'u', 'r', 'J', 'H', 'j', 'K']"),
        ),
    ]
