# Generated by Django 4.2.6 on 2023-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_uploadedfile_image_id_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='mosbefore/image\\TZVIcuCvo8/'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('user_id', 'image_id'), name='image_unique'),
        ),
    ]
