# Generated by Django 4.2.6 on 2023-11-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_uploadedfile_file_uploadedfile_image_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_mosafter',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='mosbefore/image\\wlD9zcdfT9/'),
        ),
    ]
