# Generated by Django 4.2.6 on 2023-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_uploadedfile_file_mosafter_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='mosbefore/image\\lPzTVFVZz9/'),
        ),
    ]
